### PR TITLE
Fix broken symlinks, fix additional_packages, better no_acl handling, add packages option

### PR DESCRIPTION
**Pull request by db4**
Fixes https://github.com/bincrafters/community/issues/239, https://github.com/bincrafters/community/issues/233 (partially, `cygwin` option is still broken)

### CODE REVIEW

**Comment by db4** [comment]
Oops, win32api python module is not available in CI build. Should I use `attrib` Windows utility instead? It will be much slower though...

**Comment by SSE4** [comment]
let's use attrib for now

**Comment by db4** [comment]
CI succeeded but logs shows there are some problems. Should look further...

**Comment by db4** [comment]
done

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
